###############################################################################
#                          Generated on phpdocker.io                          #

# Start docker-sync: docker-sync start
# Clean docker-sync: docker-sync clean
# Sync docker-sync: docker-sync sync
# Start containers in the background: docker-compose -f docker-compose-mac.yml up -d
# Stop containers: docker-compose -f docker-compose-mac.yml stop
# Kill containers: docker-compose -f docker-compose-mac.yml kill
# Run symfony console: docker-compose -f docker-compose-mac.yml exec php-fpm bash

###############################################################################

version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: symfony-mysql
      working_dir: /application
      volumes:
        - application-sync:/application/:nocopy
        - ./phpdocker/mysql:/etc/mysql/conf.d
      environment:
        - MYSQL_ROOT_PASSWORD=symfony
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=symfony
        - MYSQL_PASSWORD=symfony
      ports:
        - "8082:3306"
      tty: false  
      networks:
        symfony_network:
          aliases:
            - db.symfony.local

    webserver:
      image: nginx:alpine
      container_name: symfony-webserver
      working_dir: /application
      tty: false
      volumes:
          - application-sync:/application/:nocopy
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      networks:
        symfony_network:
          aliases:
            - webserver.symfony.local

    php-fpm:
      build: phpdocker/php-fpm
      container_name: symfony-php-fpm
      working_dir: /application
      volumes:
        - application-sync:/application/:nocopy
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        symfony_network:
          aliases:
            - phpfpm.symfony.local

networks:
  symfony_network:
    external: true
    
volumes:
  application-sync:
    external: true    