###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: symfony-mysql
      working_dir: /application
      volumes:
        - .:/application/:delegated
        - ./phpdocker/mysql:/etc/mysql/conf.d
      environment:
        - MYSQL_ROOT_PASSWORD=symfony
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=symfony
        - MYSQL_PASSWORD=symfony
      ports:
        - "8082:3306"
      tty: false  
      networks:
        symfony_network:
          aliases:
            - db.symfony.local

    webserver:
      image: nginx:alpine
      container_name: symfony-webserver
      working_dir: /application
      tty: false
      volumes:
          - .:/application/:delegated
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      networks:
        symfony_network:
          aliases:
            - webserver.symfony.local

    php-fpm:
      build: phpdocker/php-fpm
      container_name: symfony-php-fpm
      working_dir: /application
      volumes:
        - .:/application/:delegated
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        symfony_network:
          aliases:
            - phpfpm.symfony.local

networks:
  symfony_network:
    external: true